import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>KAZUKI </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='favicon_package/favicon.ico' />
        <link rel='apple-touch-icon' sizes='180x180' href='favicon_package/apple-touch-icon.png' />
        <link rel='icon' type='image/png' sizes='32x32' href='favicon_package/favicon-32x32.png' />
        <link rel='icon' type='image/png' sizes='16x16' href='favicon_package/favicon-16x16.png' />
        <link rel='manifest' href='favicon_package/site.webmanifest' />
        <link rel='mask-icon' href='favicon_package/safari-pinned-tab.svg' color='#5bbad5' />
        <meta name='msapplication-TileColor' content='#00aba9' />
        <meta name='theme-color' content='#ffffff' />
      </Head>

      <main>
        <h1>Hello Next.js</h1>
      </main>

      <footer></footer>
    </>
  )
}
